name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Stuff
        run: 'npm ci'
      - name: Release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.XYZ }}
          GITHUB_TOKEN: ${{ secrets.XYZ }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release